### ISSUE TITLE
Make emails not look like utter garbage

### ISSUE THREAD

**Issue by HappyNTH** [BristolSTA/uobtheatre-api#875]
**Is your feature request related to a problem? Please describe.**

Emails we send currently look and feel awful: we should fix that!

**Describe the solution you'd like**

Emails should look and feel a lot nicer than they currently are. We should remove currently clashing and inaccessible background/text colours, better add our branding, and ensure sign-offs etc. are not duplicated. 

**Additional Context**

A recently sent email:
![image](https://github.com/user-attachments/assets/f1089a86-d9e2-4a15-b0e4-1df8c40cfc60)

**Implementation Steps**

- [ ] Update basic styling of emails, such as setting background & text colours, adding logos etc.
- [ ] Audit the templates of all emails we currently automatically send
- [ ] Make clear the format emails take on Django when it comes to manual email sends, so sections don't get inadvertently duplicated.
